name: Deploy int2001 Integration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version_tag:
        required: true
        type: string
      integration_path:
        required: false
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      version_tag: ${{ inputs.version_tag }}
      integration_path: ${{ inputs.integration_path }}
    secrets: inherit
