name: Build Integration (Reusable)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      integration_id:
        required: true
        type: string
        description: 'Integration ID to build and artifact'

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_ID: ${{ github.event.inputs.integration_id }}
    steps:
      - uses: actions/checkout@v3

      - name: Check if integration folder exists
        run: |
          if [ ! -d "${{ env.INTEGRATION_ID }}" ]; then
            echo "Integration path ${{ env.INTEGRATION_ID }} does not exist."
            exit 1
          fi

      - name: Artifact Integration for ${{ env.INTEGRATION_ID }}
        run: |
          mkdir -p ./output
          zip -r ./output/integration.zip ./${{ env.INTEGRATION_ID }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-${{ env.INTEGRATION_ID }}
          path: ./output/integration.zip
