name: Build Integration

on:
  pull_request:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/${{ github.repository_owner }}
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract integration ID from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ int[0-9]+ ]]; then
            INTEGRATION_ID="${BASH_REMATCH[0]}"
            echo "Parsed integration ID: $INTEGRATION_ID"
            echo "integration_id=$INTEGRATION_ID" >> $GITHUB_OUTPUT
          else
            echo "❌ Could not parse integration ID from branch: $BRANCH_NAME"
            exit 1
          fi

      - name: Package integration folder
        run: |
          mkdir -p build
          zip -r "build/integration.zip" "${{ steps.extract.outputs.integration_id }}"

      - name: Create Dockerfile wrapper
        run: |
          cat <<EOF > build/Dockerfile
          FROM scratch
          LABEL org.opencontainers.image.title="Integration Package: ${{ steps.extract.outputs.integration_id }}"
          LABEL org.opencontainers.image.description="Versioned integration artifact"
          LABEL org.opencontainers.image.source="https://github.com/${{ github.repository }}"
          LABEL org.opencontainers.image.licenses="MIT"

          ADD integration.zip /artifact/integration.zip
          CMD ["echo", "Artifact container - nothing to run."]
          EOF

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image with :${{ github.sha }} and :latest
        run: |
          IMAGE=$GHCR/${{ steps.extract.outputs.integration_id }}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest ./build
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
