name: Build Integration

on:
  workflow_dispatch:
    inputs:
      integration_id:
        required: true
        description: "Integration ID, e.g. int2001"

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/${{ github.repository_owner }}
      INTEGRATION_ID: ${{ github.event.inputs.integration_id }}
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package integration folder
        run: |
          mkdir -p build
          zip -r "build/integration.zip" "${INTEGRATION_ID}"

      - name: Create Dockerfile wrapper
        run: |
          cat <<EOF > build/Dockerfile
          FROM scratch
          LABEL org.opencontainers.image.title="Integration Package: ${INTEGRATION_ID}"
          LABEL org.opencontainers.image.description="Versioned integration artifact for ${INTEGRATION_ID}, used to deploy via CI/CD."
          LABEL org.opencontainers.image.source="https://github.com/${{ github.repository }}"
          LABEL org.opencontainers.image.licenses="MIT"

          ADD integration.zip /artifact/integration.zip
          CMD ["echo", "Artifact container - nothing to run."]
          EOF

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image with :${{ github.sha }} and :latest
        run: |
          IMAGE=$GHCR/$INTEGRATION_ID
          docker build -t $IMAGE:$TAG -t $IMAGE:latest ./build
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
