name: Deploy on Merge to Main

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions:
  contents: write  # Needed for deploy.yml to create releases
  packages: write  # Needed for promote.yml to push tags

jobs:
  extract:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/extract-branch-information.yml

  promote:
    needs: extract
    uses: ./.github/workflows/promote.yml
    with:
      integration_id: ${{ needs.extract.outputs.integration_id }}
      target_tag: prod
    secrets: inherit

  deploy:
    needs: [extract, promote]
    uses: ./.github/workflows/deploy.yml
    with:
      integration_id: ${{ needs.extract.outputs.integration_id }}
      environment: prod
      commit_sha: ${{ github.sha }}
    secrets: inherit