name: Deploy Integration

on:
  workflow_call:
    inputs:
      integration_id:
        required: true
        type: string
        description: "Integration ID, e.g. int2001"
      environment:
        required: true
        type: string
        choices: [dev, test, prod]
        description: "Deployment environment, e.g. prod"
      deploy_code:
        required: true
        type: boolean
        default: true
      deploy_iac:
        required: true
        type: boolean
        default: true

permissions:
  contents: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/${{ github.repository_owner }}
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ inputs.integration_id }}
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull and extract integration.zip
        run: |
          container_id=$(docker create $IMAGE:$ENVIRONMENT)
          docker cp $container_id:/artifact/integration.zip ./integration.zip
          docker rm $container_id
          unzip -o integration.zip -d integration_artifact

      - name: Inspect files
        run: ls -R integration_artifact

      - name: Deploy app code
        if: inputs.deploy_code == true
        run: echo "Deploying Logic App or Function App..."

      - name: Deploy infrastructure
        if: inputs.deploy_iac == true
        run: echo "Deploying Terraform/Bicep..."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-${{ inputs.integration_id }}-${{ github.sha }}
          name: "Integration: ${{ inputs.integration_id }}"
          body: |
            ## Integration: ${{ inputs.integration_id }}
            - **Environment:** `${{ inputs.environment }}`
            - **Deploy Code:** `${{ inputs.deploy_code }}`
            - **Deploy IaC:** `${{ inputs.deploy_iac }}`
            - **Deployed by:** @${{ github.actor }}
            - **Package:** [View](https://github.com/users/${{ github.repository_owner }}/packages/container/${{ inputs.integration_id }})
