# .github/workflows/deploy.yml
name: Deploy Integration v2

on:
  workflow_dispatch:
    inputs:
      integration_id:
        required: true
      tag:
        required: true
        description: 'e.g. test or prod'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.integration_id }}

    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract ZIP from container
        run: |
          container_id=$(docker create $IMAGE:${{ github.event.inputs.tag }})
          docker cp $container_id:/artifact/integration.zip ./integration.zip
          docker rm $container_id
          unzip -o integration.zip -d extracted

      - name: Inspect extracted files (debug)
        run: ls -R extracted

      # - name: Deploy with Azure CLI or Terraform
      #   run: az deployment group create ... OR terraform apply
