name: Promote Integration v2

on:
  workflow_call:
    inputs:
      integration_id:
        required: true
        description: 'Integration ID, e.g. int2001'
      target_tag:
        required: true
        type: string

permissions:
  packages: write
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/${{ github.repository_owner }}
      INTEGRATION_ID: ${{ github.event.inputs.integration_id }}
    steps:
      - name: Set image name
        id: meta
        run: echo "image=$GHCR/$INTEGRATION_ID" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Promote image tag 'latest' to 'prod'
        run: |
          IMAGE=${{ steps.meta.outputs.image }}
          SOURCE_TAG=latest
          TARGET_TAG=prod

          echo "Pulling $IMAGE:$SOURCE_TAG"
          docker pull $IMAGE:$SOURCE_TAG

          echo "Tagging $IMAGE:$SOURCE_TAG as $IMAGE:$TARGET_TAG"
          docker tag $IMAGE:$SOURCE_TAG $IMAGE:$TARGET_TAG

          echo "Pushing $IMAGE:$TARGET_TAG"
          docker push $IMAGE:$TARGET_TAG
