name: Promote Integration

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [test, prod]
      integration_id:
        required: true
        description: 'Integration ID, e.g. int2001'

permissions:
  contents: write  # Needed for git push and gh release edit

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: integration-${{ github.event.inputs.integration_id }}
          path: ./integration_artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-${{ github.event.inputs.integration_id }}-${{ github.sha }}
          files: ./integration_artifact/integration.zip

      - name: Append environment info to GitHub release
        run: |
          VERSION_TAG="v-${{ github.event.inputs.integration_id }}-${{ github.sha }}"
          current_body=$(gh release view "$VERSION_TAG" --json body -q ".body")
          timestamp=$(date +'%Y-%m-%d %H:%M:%S')
          updated_body=$(
          cat <<EOF
          ✅ Deployed to: ${{ github.event.inputs.environment }} at ${timestamp} by @${{ github.actor }}

          ${current_body}
          EOF
          )
          gh release edit "$VERSION_TAG" --notes "$updated_body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
