name: Promote Integration v2

on:
  workflow_call:
    inputs:
      integration_id:
        required: true
        type: string
        description: 'Integration ID, e.g. int2001'
      target_tag:
        required: true
        type: string
        description: 'Environment tag to promote to, e.g. dev, test, prod'

permissions:
  packages: write
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/${{ github.repository_owner }}
      INTEGRATION_ID: ${{ inputs.integration_id }}
      TARGET_TAG: ${{ inputs.target_tag }}
      SOURCE_TAG: ${{ github.sha }} # current commit hash
    steps:
      - name: Set image name
        id: meta
        run: echo "image=$GHCR/$INTEGRATION_ID" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Verify image with commit SHA exists
        run: |
          IMAGE=${{ steps.meta.outputs.image }}
          echo "Checking $IMAGE:$SOURCE_TAG..."
          if ! docker pull $IMAGE:$SOURCE_TAG; then
            echo "::error ::Image $IMAGE:$SOURCE_TAG not found. You probably forgot to build it."
            exit 1
          fi

      - name: Promote image to $TARGET_TAG
        run: |
          IMAGE=${{ steps.meta.outputs.image }}
          docker tag $IMAGE:$SOURCE_TAG $IMAGE:$TARGET_TAG
          docker push $IMAGE:$TARGET_TAG
          echo "Image $IMAGE:$TARGET_TAG promoted successfully."
