name: Promote on Label

permissions:
  packages: write
  contents: read
  id-token: write
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  extract:
    uses: ./.github/workflows/extract-branch-information.yml

  determine_target_tag:
    needs: extract
    runs-on: ubuntu-latest
    outputs:
      integration_id: ${{ needs.extract.outputs.integration_id }}
      target_tag: ${{ steps.tag.outputs.target_tag }}

    steps:
      - name: Determine tag based on label
        id: tag
        run: |
          LABELS_JSON='${{ toJson(github.event.pull_request.labels) }}'
          echo "Labels: $LABELS_JSON"

          if [[ "$LABELS_JSON" == *"deploy-dev"* ]]; then
            echo "target_tag=dev" >> $GITHUB_OUTPUT
          elif [[ "$LABELS_JSON" == *"deploy-test"* ]]; then
            echo "target_tag=test" >> $GITHUB_OUTPUT
          else
            echo "No valid label found"
            exit 1
          fi

  promote:
    needs: determine_target_tag
    uses: ./.github/workflows/promote.yml
    with:
      integration_id: ${{ needs.determine_target_tag.outputs.integration_id }}
      target_tag: ${{ needs.determine_target_tag.outputs.target_tag }}
    secrets: inherit

  remove_label:
    needs: [determine_target_tag, promote]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Actions Ecosystem Remove Labels
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            deploy-dev
            deploy-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
