name: Rollback Integration

on:
  workflow_dispatch:
    inputs:
      integration_id:
        required: true
        description: 'Integration ID, e.g. int2001'
      environment:
        required: true
        type: choice
        options: [test, prod]
      version_tag:
        required: true
        description: 'Version tag to rollback to, e.g. v-int2001-<sha>'

permissions:
  contents: read

jobs:
  rollback:
    uses: ./.github/workflows/deploy.yml
    with:
      integration_id: ${{ github.event.inputs.integration_id }}
      environment: ${{ github.event.inputs.environment }}
      tag: ${{ github.event.inputs.version_tag }}
    secrets: inherit
